language: java

branches:
  only:
    - master

jdk:
  - oraclejdk8

before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"

addons:
  sonarcloud:
    organization: "jmrozanec-github"
    
script:
   - > 
     if [ "$TRAVIS_PULL_REQUEST" != "false" ];
     then mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar --settings target/travis/settings.xml -Dsettings.security=target/travis/settings-security.xml -Dmaven.javadoc.skip=true;
     fi
   - > 
     if [ "$TRAVIS_PULL_REQUEST" = "false" ];
     then mvn org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar deploy --settings target/travis/settings.xml -Dsettings.security=target/travis/settings-security.xml -Dmaven.javadoc.skip=true;
     fi

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - mvn cobertura:cobertura coveralls:cobertura
  - bash <(curl -s https://codecov.io/bash)
